### ISSUE TITLE
[Bug] Upload Multiple only uploads the last file added when selecting from multiple file browsers.

### ISSUE THREAD

**Issue by NuktukDev** [Laravel-Backpack/community-forum#1263]
# Bug report

**Please note:** All issues must be submitted in **English**. If not, they will be closed automatically.

### What I did

Click the upload multiple field, choose a file, confirm.
Click the upload multiple field, choose another file, confirm.

I now see two files selected.

### What I expected to happen

Both files would be uploaded.

### What happened

Only the last file I chose is uploaded.

### What I've already tried to fix it

Reading the docs.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
8.3.12

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, ldap, exif, msgpack, mysqli, pcov, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, redis, swoole, Zend OPcache, xdebug

### LARAVEL VERSION:
10.48.22.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.6
backpack/crud: 6.7.44
backpack/generators: v4.0.7
backpack/medialibrary-uploaders: 1.2.1
backpack/pro: 2.2.21
backpack/theme-tabler: 1.2.13
### Additional Information

Here's some more info that could be helpful in reproducing or debugging: 
- **Environment details (e.g., operating system, web server, browser):** laravel forge and local
- **Steps to reproduce the issue (if possible):** Click the upload multiple field, choose a file, confirm.
Click the upload multiple field, choose another file, confirm.
- **Relevant error logs or screenshots (if any):** ??
 
**Note:** Issues that cannot be reproduced or lack necessary details to diagnose could be closed.

**Comment by NuktukDev** [comment]
That is a different bug.

**Comment by karandatwani92** [comment]
Hey @NuktukDev 

Can you share your field definition? To know -  what exact field, uploader, and attributes you used, and that will help me reproduce the issue.

**Comment by NuktukDev** [comment]
> Hey @NuktukDev
> 
> Can you share your field definition? To know - what exact field, uploader, and attributes you used, and that will help me reproduce the issue.

```
CRUD::field([   // Browse
            'name'  => 'documents',
            'label' => 'Documents',
            'type'  => 'upload_multiple',
            'withFiles' => true
        ]);
```

**Comment by karandatwani92** [comment]
Hey @NuktukDev 

Thanks for reporting the bug. Your code helped me to confirm the Bug.

**Comment by karandatwani92** [comment]
Hey @NuktukDev 

Thanks for reporting the bug. Your code helped me confirm the bug.

**Comment by pxpm** [comment]
@karandatwani92 isn't this fixed in v7 already ? It should, I hope 🙏

**Comment by NuktukDev** [comment]
> @karandatwani92 isn't this fixed in v7 already ? It should, I hope 🙏

Does that mean there would be no patch for v6? I already paid for v6 unfortunately

**Comment by pxpm** [comment]
> > @karandatwani92 isn't this fixed in v7 already ? It should, I hope 🙏
> 
> Does that mean there would be no patch for v6? I already paid for v6 unfortunately

There is no payment between v6 and v7. Multiple upload, as also single upload are part of the free core so you can just upgrade the versions. 👍 

Even if they were part of paid packages, if you have an active license you can use the same license to update those packages. The license is not "per version", but it's 1 year of updates. Everything released in a 1 year timeframe from your license start date is "yours". 

Cheers

**Comment by NuktukDev** [comment]
Thanks, is there anyway I could get the fix now? I'm not sure v7 is out, I'd even be willing to update my vendor folder temporarily with a hotfix.

> > > @karandatwani92 isn't this fixed in v7 already ? It should, I hope 🙏
> > 
> > 
> > Does that mean there would be no patch for v6? I already paid for v6 unfortunately
> 
> There is no payment between v6 and v7. Multiple upload, as also single upload are part of the free core so you can just upgrade the versions. 👍
> 
> Even if they were part of paid packages, if you have an active license you can use the same license to update those packages. The license is not "per version", but it's 1 year of updates. Everything released in a 1 year timeframe from your license start date is "yours".
> 
> Cheers

**Comment by karandatwani92** [comment]
Hey @pxpm 

It's not fixed there. I just tested the `next` branch to confirm. The problem is in the `upload_multiple ` field, not the uploaders. 
The POST request only includes one file by following these steps:
- Click the `upload_multiple` field, and choose a file.
- Click the same `upload_multiple` field again, choose another file and now press save.

You will notice only the last file selected is in the request. Can you please confirm at your end?

**Comment by pxpm** [comment]
Hey @karandatwani92 and @NuktukDev 

This is not a bug, it's just the way `type="file"` inputs work. 
After the selection it's not possible to "mess" with the input again, so every time the file selection is open, what's selected is what's sent to the browser. There is technically no way of "merging" multiple file selections. 

For that behavior you should use the `dropzone`, that stores "temporary files" after each selection, so you can select 1 file at first, then 2, then again 1, and all 4 files will be saved in the server. 

Hope I've clarified your questions. 🙏 

Cheers
