### ISSUE TITLE
Target class [Backpack\CRUD\app\Http\Middleware\AuthenticateSession] does not exist.

### ISSUE THREAD

**Issue by tudoavinfo** [Laravel-Backpack/community-forum#343]
It's not you, it's me.
Target class [Backpack\CRUD\app\Http\Middleware\AuthenticateSession] does not exist.

i am getting this error when uploading my site to production on server.
The error occurs after admin login on all dashboard pages. Locally it works normally, what could be going on?

**Comment by tabacitu** [comment]
Sounds like you're running Laravel 8 in production, but Laravel 9 on local? Is that possible?

If that's the case, a "composer update" on the one that's not working should fix it.

**Comment by munjaldevelopment** [comment]
Yes, i face same error with laravel 9 with backpack 5.4.*. You need to
downgrade your laravel version and run composer update after remove vendor
folder and all files of bootstrap/cache folder.

Thanks,
Munjal

**Comment by tabacitu** [comment]
No no no. That's unacceptable - we can't ask people to downgrade their Laravel version.

@tudoavinfo can you please run a "php artisan backpack:version" on both systems, and let us know the output?

**Comment by munjaldevelopment** [comment]
@tabacitu below is the output of "php artisan backpack:version".

## PHP VERSION:
PHP 8.1.7 (cli) (built: Jun  7 2022 21:45:53) (ZTS Visual C++ 2019 x64)

### LARAVEL VERSION:
***@***.***

### BACKPACK VERSION:
***@***.***

I am still getting this error on fresh installation.

[image: image.png]

**Comment by munjaldevelopment** [comment]
I just tried debugging & found `if (class_exists('\Illuminate\Contracts\Session\Middleware\AuthenticatesSessions', false))` is causing issue. If we comment this line, it works fine on laravel 9 too.

**Comment by tudoavinfo** [comment]
Local:
### PHP VERSION:
PHP 8.1.12 (cli) (built: Oct 28 2022 17:39:57) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.12, Copyright (c), by Zend Technologies
    with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
v9.39.0@67e674709e1e7db14f304a871481f310822d68c5

### BACKPACK VERSION:
5.4.11@ffbadcdb6478822646600b2cd763490caa927155

Production:

### PHP VERSION:
PHP 8.1.13 (cli) (built: Dec 18 2022 23:47:35) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.45.1@faeb20d3fc61b69790068161ab42bcf2d5faccbc

### BACKPACK VERSION:
5.4.12@6ff47ed84735c672cf08c763c633419beea8e392

**Comment by tudoavinfo** [comment]
it worked by downgrading the backpack version, I left it fixed at the same version I was using local: "backpack/crud":"5.4.11" and "laravel/framework": "9.39.0",,
ran composer update and php crafter config:clear. php in version 8.1.13 i.e. php version does not influence. Thanks a lot for the help

**Comment by tabacitu** [comment]
I could also reproduce this. I've just installed a FRESH laravel instance, then Backpack\CRUD on top of it (no PRO, no DevTools), and I get this error now:

![](https://cdn.discordapp.com/attachments/945282719246589993/1057969852624678982/CleanShot_2022-12-29_at_12.34.15.png)

https://flareapp.io/share/bP98ONZm#F50


![](https://cdn.discordapp.com/attachments/945282719246589993/1057969990973792337/CleanShot_2022-12-29_at_12.34.54.png)

**Comment by tabacitu** [comment]
Thanks for reporting this everyone! Pedro fixed it in https://github.com/Laravel-Backpack/CRUD/pull/4861 so a `composer update` should get you CRUD 5.4.13 which has this fixed! Let us know if you're having any more problems with it.

Cheers!
